import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import Image from "next/image";
import { type Icon } from "@prisma/client";

const CollectionPage: NextPage = () => {
  const icons = api.icons.getIcons.useQuery();

  return (
    <>
      <Head>
        <title>Your Icons</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto mt-24 flex flex-col items-center gap-8 px-8">
        <h1 className="text-4xl">Your Icons</h1>
        <ul className="grid grid-cols-2 gap-8 sm:grid-cols-4 sm:gap-12">
          {icons.data?.map((icon: Icon) => (
            <li key={icon.id} className="rounded overflow-hidden">
              <Image
                className="w-full"
                width="100"
                height="100"
                alt={icon.prompt ?? "Icon"}
                src={`https://leighs-icon-generator.s3.amazonaws.com/${icon.id}`}
              />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};



export default CollectionPage;
