import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import Image from "next/image";
import { type Icon } from "@prisma/client";

const CollectionPage: NextPage = () => {
  
  const icons = api.icons.getIcons.useQuery();

  return (
    <>
      <Head>
        <title>Your Icons</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex  mt-24 flex-col items-center px-8 gap-4 min-h-screen">
        <h1 className="text-4xl">Your Icons</h1>
        <ul className="grid grid-cols-2 snap-mandatory">
          {icons.data?.map((icon : Icon) => (
            <li key={icon.id}>
              <Image
                width="100"
                height="100"
                alt={icon.prompt ?? "Icon"}
                src={`https://leighs-icon-generator.s3.amazonaws.com/${icon.id}`}
              />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default CollectionPage;
