import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import Image from "next/image";
import { type Icon } from "@prisma/client";
import { CommunityHero } from "~/components/CommunityHero";

const CollectionPage: NextPage = () => {
  const icons = api.icons.getCommunityIcons.useQuery();

  function makeVariation(){
    console.log("makeVariation")
  }

  return (
    <>
      <Head>
        <title>Community Icons</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommunityHero></CommunityHero>
      <main className="container mx-auto mt-24 flex flex-col items-center gap-8 px-8">
        <h1 className="text-4xl">Community Assets</h1>
        <div className="grid grid-cols-2 gap-8 sm:grid-cols-4 sm:gap-12">
          {icons.data?.map((icon: Icon) => (
            <div key={icon.id} className="overflow-hidden rounded shadow-lg">
              <Image
                className="w-full"
                width="100"
                height="100"
                alt={icon.prompt ?? "Icon"}
                src={`https://leighs-icon-generator.s3.amazonaws.com/${icon.id}`}
              />
              <div className="flex flex-col p-4">
                <p className="text-gray-600">{icon.prompt}</p>
                <div className="mt-2 flex flex-wrap gap-2">
                  {icon.promptOptions?.map((option) => (
                    <span
                      key={option}
                      className="rounded bg-blue-100 px-2.5 py-0.5 text-xs font-medium text-blue-800 dark:bg-blue-900 dark:text-blue-300"
                    >
                      {option}
                    </span>
                  ))}
                </div>
                <button
                  className="mt-4 rounded bg-blue-500 px-4 py-2 text-white hover:bg-blue-600"
                  // eslint-disable-next-line @typescript-eslint/no-misused-promises
                  onClick={makeVariation()}
                >
                  Make Variation
                </button>
              </div>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default CollectionPage;
