import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import Image from "next/image";
import { type Icon } from "@prisma/client";
import { CommunityHero } from "~/components/CommunityHero";
import CommunityItem from "~/components/CommunityItem";

const CollectionPage: NextPage = () => {
  const icons = api.icons.getCommunityIcons.useQuery();

  return (
    <>
      <Head>
        <title>Community Icons</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommunityHero></CommunityHero>
      <main className="container mx-auto mt-24 flex flex-col items-center gap-8 px-8">
        <h1 className="text-4xl">Community Assets</h1>
        <div className="grid grid-cols-2 gap-8 sm:grid-cols-4 sm:gap-12">
          {icons.data?.map((icon: Icon) => (
            <div key={icon.id} className="overflow-hidden rounded shadow-lg">
              <Image
                className="w-full"
                width="100"
                height="100"
                alt={icon.prompt ?? "Icon"}
                src={`https://leighs-icon-generator.s3.amazonaws.com/${icon.id}`}
              />
              <div className="flex flex-col p-4">
                <h2 className="text-xl font-semibold">
                  Generated By: Leigh Briody
                </h2>
                <p className="text-gray-600">{icon.prompt}</p>
                <div className="mt-2 flex flex-wrap gap-2">
                  <span className="rounded bg-blue-100 px-2.5 py-0.5 text-xs font-medium text-blue-800 dark:bg-blue-900 dark:text-blue-300">
                    Icon
                  </span>
                  <span className="rounded bg-blue-100 px-2.5 py-0.5 text-xs font-medium text-blue-800 dark:bg-blue-900 dark:text-blue-300">
                    Dark Background
                  </span>
                  <span className="rounded bg-blue-100 px-2.5 py-0.5 text-xs font-medium text-blue-800 dark:bg-blue-900 dark:text-blue-300">
                    Blue Color
                  </span>
                  <span className="rounded bg-blue-100 px-2.5 py-0.5 text-xs font-medium text-blue-800 dark:bg-blue-900 dark:text-blue-300">
                    Circle
                  </span>
                  <span className="rounded bg-blue-100 px-2.5 py-0.5 text-xs font-medium text-blue-800 dark:bg-blue-900 dark:text-blue-300">
                    flat
                  </span>
                </div>
                <button className="mt-4 rounded bg-blue-500 px-4 py-2 text-white hover:bg-blue-600">
                  Make Variation
                </button>
              </div>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default CollectionPage;
