import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { PrimaryLinkButton } from "~/components/PrimaryLinkButton";

function HeroBanner() {
  return (
    <section className="mt-12 mb-24 grid grid-cols-1 sm:grid-cols-2 gap-12 px-8 text-4xl">
      <div className="flex flex-col gap-4">
        <h1 className="text-6xl">Generate Icons with a click of a button</h1>
        <p className="text-2xl">
          Use AI to generate icons instead of paying a designer and waiting for
          them...
        </p>
        <PrimaryLinkButton href={"/generate"} className="self-start">
          Generate your Icons
        </PrimaryLinkButton>
      </div>
      <Image
        className="order-first sm:-order-none"
        src="/banner.png"
        alt="hero image"
        width="300"
        height="300"
      ></Image>
    </section>
  );
}

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex  flex-col items-center justify-center">
        <HeroBanner />
      </main>
    </>
  );
};

export default HomePage;
